from collections.abc import Mapping, Sequence
from typing import Any

Rows = Sequence[Sequence[float]]
FrameLike = Frame | Table | Rows

def version() -> str: ...

class Frame:
    @staticmethod
    def from_rows(rows: Rows, columns: Sequence[str] | None = ...) -> Frame: ...
    @staticmethod
    def from_numpy(array: Any) -> Frame: ...
    @staticmethod
    def from_pandas(df: Any) -> Frame: ...
    def columns(self) -> list[str]: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __len__(self) -> int: ...

class Table:
    @staticmethod
    def from_csv(path: str) -> Table: ...
    @staticmethod
    def from_parquet(path: str) -> Table: ...
    @staticmethod
    def from_frame(frame: Frame) -> Table: ...
    def to_frame(self) -> Frame: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __len__(self) -> int: ...

class Profile:
    @staticmethod
    def of(data: Frame | Table) -> Profile: ...
    @staticmethod
    def of_with_target(data: Frame | Table, target: str) -> Profile: ...
    def to_html(self, path: str) -> None: ...

class StandardScaler: ...
class MinMaxScaler: ...
class OneHotEncoder: ...
class SimpleImputer:
    def __init__(self, strategy: str | None = ...) -> None: ...
    @staticmethod
    def median() -> SimpleImputer: ...
    @staticmethod
    def mean() -> SimpleImputer: ...
class RandomForest:
    def __init__(self, n_trees: int = ..., max_depth: int | None = ...) -> None: ...
class LinearRegression: ...
class Knn:
    def __init__(self, k: int = ...) -> None: ...
class Svc:
    def __init__(self, c: float = ..., gamma: float | None = ...) -> None: ...
    @staticmethod
    def rbf(gamma: float = ..., c: float = ...) -> Svc: ...
class NaiveBayes: ...
class OnnxModel:
    def __init__(self, path: str) -> None: ...

class Explainer:
    @staticmethod
    def kernel() -> Explainer: ...
    def nsamples(self, n: int) -> Explainer: ...
    def background(self, n: int) -> Explainer: ...

class Pipeline:
    def step(self, name: str, transformer: object) -> Pipeline: ...
    def estimator(self, name: str, estimator: object) -> Pipeline: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> None: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def evaluate(self, data: FrameLike, labels: Sequence[float]) -> dict[str, float]: ...
    def steps(self) -> list[str]: ...
    def explain(self, data: FrameLike, explainer: Explainer) -> list[tuple[str, float]]: ...
    def export_onnx(self, path: str) -> None: ...

class KFold:
    def __init__(self, k: int) -> None: ...
class StratifiedKFold:
    def __init__(self, k: int) -> None: ...
class GridSearch:
    def __init__(self, pipeline: Pipeline, params: Mapping[str, Sequence[int | float | bool]], *, cv: KFold | StratifiedKFold | None = ..., scoring: str = ...) -> None: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> SearchResult: ...
class SearchResult:
    @property
    def best_score(self) -> float: ...
    def best_params(self) -> dict[str, int | float | bool]: ...
    def predict(self, data: FrameLike) -> list[float]: ...

class Voting:
    def __init__(self, kind: str = ..., task: str = ...) -> None: ...
    def add(self, name: str, pipeline: Pipeline) -> Voting: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> None: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def export_onnx(self, path: str) -> None: ...

class Bagging:
    def __init__(self, base: Pipeline, n_estimators: int = ..., seed: int = ..., task: str = ...) -> None: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> None: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def export_onnx(self, path: str) -> None: ...

class Boosting:
    def __init__(self, base: Pipeline, n_estimators: int = ..., learning_rate: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> None: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def export_onnx(self, path: str) -> None: ...

class Stacking:
    def __init__(self, meta: Pipeline, cv: KFold | StratifiedKFold | int | None = ...) -> None: ...
    def base(self, name: str, pipeline: Pipeline) -> Stacking: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> None: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def export_onnx(self, path: str) -> None: ...

class AutoML:
    @staticmethod
    def classifier() -> AutoML: ...
    @staticmethod
    def regressor() -> AutoML: ...
    def budget_trials(self, trials: int) -> AutoML: ...
    def scoring(self, metric: str) -> AutoML: ...
    def cv(self, cv: KFold | StratifiedKFold | int) -> AutoML: ...
    def seed(self, seed: int) -> AutoML: ...
    def no_ensemble(self) -> AutoML: ...
    def ensemble_size(self, size: int) -> AutoML: ...
    def ensemble_kinds(self, kinds: Sequence[str]) -> AutoML: ...
    def prefer_ensemble_on_tie(self) -> AutoML: ...
    def parallel(self) -> AutoML: ...
    def fit(self, data: FrameLike, labels: Sequence[float]) -> AutoMLResult: ...

class AutoMLResult:
    @property
    def best_label(self) -> str: ...
    @property
    def best_score(self) -> float: ...
    @property
    def is_ensemble(self) -> bool: ...
    def leaderboard(self) -> str: ...
    def ensemble_failures(self) -> list[tuple[str, str]]: ...
    def predict(self, data: FrameLike) -> list[float]: ...
    def export_onnx(self, path: str) -> None: ...
